### ISSUE TITLE
Not complete steps for upload document in share point 

### ISSUE THREAD

**Issue by lokesh19931** [jakub-klapka/laravel-sharepoint-upload-client#1]
Hello Extension holder,

I Need to upload document on sharepoint so...we face problem regarding to that. acutally in plugin readme file all steps are not available. can you share all steps for upload document in shared point using laravel 5.5  version.

Thanks

**Comment by jakub-klapka** [comment]
Hello,
how far did you get in the procedure? What exactly is failing?

Jakub

**Comment by lokesh19931** [comment]
Hello,
How to get authcode Like that $auth_code = $_REQUEST['code'];. Can you help me for upload document in sharepoint site using laravel 5.5.

**Comment by jakub-klapka** [comment]
You will get this code as part of URL, on which is user redirected after making consent on microsoft login site. It will always be available as `$_REQUEST['code']`, if the consent is correct.
To put it another way:
1. You will go to microsoft oauth site on URL: `$client->getUserConsentUri()`
2. There, you will make consent, that this app can upload files to sharepoint (simply log in with admin account and press Allow)
3. After that, microsoft will redirect you to your redirect uri and will append token as code= parameter in URL. For example, you will be redirected to https://yourapp.com/?code=123456789.
4. You just need to save that code into your DB (or any other storage) and than, it can be used to upload files

To have all of that working, you have to register your app on sharepoint register page, which is located on your sharepoint site URL with /_layouts/15/appregnew.aspx appended. For example: https://contoso.sharepoint.com/sites/MySite/_layouts/15/appregnew.aspx

Hope, that it's clearer now. Jakub

**Comment by lokesh19931** [comment]
Hello,
Not found "code". can you help to generate code. I'm following those steps:
 $site_url='https://mysite.sharepoint.com/sites/docupload/default.aspx';
    $app_id='xxxxx-xxxx-4657-xxxxx-666dec9d955e';
    $app_secret='xxxxxxxxxxxxxxx/xxxxxxxxxxxxxxx=';
    $redirect_uri='https://localhost/phpappweb/index.php';
//    $redirect_uri='';
    $client = $this->sharepointClient->makeClient( $site_url, $app_id, $app_secret, $redirect_uri );
    $url = $client->getUserConsentUri();
    return redirect("$url");
then this redirect on microsoft login account but not found how to generate code. can you help me to upload document in sharepoint.

**Comment by jakub-klapka** [comment]
You do not generate the "code". Microsoft will return that to you after successfull consent.
What do you see on microsoft login page? Did you register your app on https://mysite.sharepoint.com/sites/docupload/_layouts/15/appregnew.aspx? Did you put https://localhost/phpappweb/index.php as your Redirect URI in the registration form?

**Comment by lokesh19931** [comment]
Hello, 
Thanks for valuable reply.

I found error. please see attached image and help me.
![image](https://user-images.githubusercontent.com/34569960/34208246-b1913f3c-e5b3-11e7-8a5c-8e96a33cb485.png)

Thanks

**Comment by jakub-klapka** [comment]
It seems, that you do not providing correct refresh token.
The flow should be in this way:
1. You register your app on appregnew.aspx on your sharepoint site
2. You follow `$client->getUserConsentUri()` URL to login, give consent and get back Auth Code
3. You convert auth code to refresh token by `$client->getRefreshTokenFromAuthCode( $auth_code )`. You probably want to have this logic on your Redirect URI (you can create route on your laravel page for specificaly that)
4. You have to save the refresh token (in database, file, etc.)
5. Whenever you need to upload file, you have to provide the refresh token (from DB or wherever you have it). It won't work without that.

**Comment by lokesh19931** [comment]
Hi, 

Thanks for help.
When we used those steps then founded some errors: please help me for that error .
Please find attached image
![image](https://user-images.githubusercontent.com/34569960/34381162-c1bfb8ec-eb2c-11e7-90d4-321472c50e59.png)

**Comment by jakub-klapka** [comment]
Hello,
it seems, that you set site_url in makeClient() to `...sites/docupload` but in uploadFile() you are using `sites/Documents`. You have to upload file to same site as you specify in the client.

Hope that helps, Jakub

**Comment by lokesh19931** [comment]
Hello,
Thanks for valuable reply.
when i try again then face these type errors. Please see screen shot
![image](https://user-images.githubusercontent.com/34569960/34429518-2813b74e-ec7f-11e7-8a87-64a840becd8b.png)

**Comment by jakub-klapka** [comment]
You are not providing valid refresh_token within uploadFile().

**Comment by faboe** [comment]
Hello Jakub, I need help for uploading files to my sharepoint site. 
i did everything as you say in your docs, but when i try to upload i get this error. 
--see screen shot--
![captura de pantalla 2019-02-06 a la s 18 05 07](https://user-images.githubusercontent.com/47404517/52419809-77924580-2ab6-11e9-81ea-35adfe9830ba.png)

And here is my line 32.
![captura de pantalla 2019-02-07 a la s 09 01 31](https://user-images.githubusercontent.com/47404517/52420126-0dc66b80-2ab7-11e9-88a8-00c9575734b5.png)

in the function uploadFile() in the 3rd parameter is it the path to the file i want to upload? 
and in function readStream() is it the path to file as in my 3rd parameter in uploadFile function? 

 I'll appreciate your help. Thank you and have a good day.

**Comment by jakub-klapka** [comment]
Hello,
the third parameter of uploadFile() is stream of your file. In my example, I'm expecting to already have `$this->transfer_storage` setup as Laravel's File Storage. Which is probably not your case.

The easiest way how to do this will be to setup local Filesystem Storage, which you can do in your `config/filesystems.php`. There, you should have `local` filesystem with root path to your files. More on that here: https://laravel.com/docs/5.7/filesystem
After you do that, you can use Laravel's Facade to easily read stream of your file like this: `\Storage::disk('local')->readStream('document.xlsx')`

All about storages can be found on the same link: https://laravel.com/docs/5.7/filesystem

**Comment by shalemperez** [comment]
> You will get this code as part of URL, on which is user redirected after making consent on microsoft login site. It will always be available as `$_REQUEST['code']`, if the consent is correct.
> To put it another way:
> 
> 1. You will go to microsoft oauth site on URL: `$client->getUserConsentUri()`
> 2. There, you will make consent, that this app can upload files to sharepoint (simply log in with admin account and press Allow)
> 3. After that, microsoft will redirect you to your redirect uri and will append token as code= parameter in URL. For example, you will be redirected to https://yourapp.com/?code=123456789.
> 4. You just need to save that code into your DB (or any other storage) and than, it can be used to upload files
> 
> To have all of that working, you have to register your app on sharepoint register page, which is located on your sharepoint site URL with /_layouts/15/appregnew.aspx appended. For example: https://contoso.sharepoint.com/sites/MySite/_layouts/15/appregnew.aspx
> 
> Hope, that it's clearer now. Jakub

I am stuck in step 3, after allowing the app i get redirected but with no parameters, some advice?

**Comment by shalemperez** [comment]
> You will get this code as part of URL, on which is user redirected after making consent on microsoft login site. It will always be available as `$_REQUEST['code']`, if the consent is correct.
> To put it another way:
> 
> 1. You will go to microsoft oauth site on URL: `$client->getUserConsentUri()`
> 2. There, you will make consent, that this app can upload files to sharepoint (simply log in with admin account and press Allow)
> 3. After that, microsoft will redirect you to your redirect uri and will append token as code= parameter in URL. For example, you will be redirected to https://yourapp.com/?code=123456789.
> 4. You just need to save that code into your DB (or any other storage) and than, it can be used to upload files
> 
> To have all of that working, you have to register your app on sharepoint register page, which is located on your sharepoint site URL with /_layouts/15/appregnew.aspx appended. For example: https://contoso.sharepoint.com/sites/MySite/_layouts/15/appregnew.aspx
> 
> Hope, that it's clearer now. Jakub

How can i get this on my sharepoint: 

`
'/sites/mySite/myLibrary/',
`

**Comment by jakub-klapka** [comment]
Just follow instructions :) Where did you get stuck?

**Comment by Shruthishetty93** [comment]
Hello Jakub, I need help for uploading files to my sharepoint site.
i did everything as you say in your docs, but when i try to upload i get this error.
Getting error as:

**Client error: `POST https://accounts.accesscontrol.windows.net/9d4a4a83-3fb3-4b55-9de8-1f3197f8b1f3/tokens/OAuth/2` resulted in a `400 Bad Request` response:\n{\"error\":\"invalid_grant\",\"error_description\":\"AADSTS70000: Provided grant is invalid or malformed. Trace ID: f7b65177-e5 (truncated...)\n**

**_my code_**
`$file = $request->file('file');
    	$newFileName = Helpers::reformatFileName($file->getClientOriginalName());
    	$allowedMimeTypes = ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf', 'application/docx'];
		if (!in_array($file->getMimeType(), $allowedMimeTypes)) {
				return "File type not allowed.";
			}
		$filePath = 'submittal-files/' . $request->input('id');
		$site_url = 'https://theglaciergroup.sharepoint.com';

		$library = 'Documents'; // Replace with your SharePoint library name
		$folder = 'CQ Development'; // Replace with your SharePoint folder name
		$endpoint = "$site_url/_api/web/GetFolderByServerRelativeUrl('/$library/$folder')/Files/add(url='$newFileName',overwrite=true)";

		//sharepoint
		$app_id = 'af3e733e-aff9-426d-87f1-ec27d699b502';
		$app_secret = 'MN+TrP8t864md7ovBnwS/PD3I3cncP6DbeYlSMreqyg=';
		$redirect_uri = 'https://conquer.tgg';
		$client = $this->sharepointClient->makeClient( $site_url, $app_id, $app_secret, $redirect_uri);
		$url = $client->getUserConsentUri();
		$auth_code = 'PAQABAAEAAAAtyolDObpQQ5VtlI4uGjEPSxAdxpjJBhHs_aK2NwCVnK5CHKtN_OzqVup0hPEQKp5k_3xo9gNhBXUBp7ErdsNvTwDF1erTf5iGtivKATZCkRciqXqOK71bEwdgBxy1MwgmMekV-4qN1m5nUeJu4WKQmdxXvci7dDZGkl1qDQlZPC4lTIqGFhw-zK9_5R2cBZxLQBiSac8aFKYQRatXt91XkW88P69A-4YOoeBresKsjVkHMrF8r4KgcGe4fH0-QxFXN18V_1qELCW807xMBBhUjtTmZorfuZJOvEt4vYDRhAUHhNPFvNl9R4AwRsPGEl1LiU-X4sZvyLMFNTZCwpPjIAA';
		$refreshToken = $client->getRefreshTokenFromAuthCode($auth_code);
		// Upload the file to SharePoint
		$upload_result = $client->uploadFile(
			$refreshToken,
			$endpoint,
			'https://theglaciergroup.sharepoint.com/Shared%20Documents/Forms/AllItems.aspx?viewpath=%2FShared%20Documents%2FForms%2FAllItems%2Easpx&id=%2FShared%20Documents%2FCQ%20Development&viewid=75380876%2D96c8%2D4d78%2D86e6%2Ddb6f24b940f9',
			$filePath,
			\Storage::disk('local')->readStream($filePath));`
			
	here i created app id & secret in both sharepoint and azure. 
	Whether should i mention azure endpoint. 
	if need where should i mention it. 
	please help me out from this.
