### ISSUE TITLE
Can't get site realm

### ISSUE THREAD

**Issue by thebaud2u** [jakub-klapka/laravel-sharepoint-upload-client#2]
Hi,

I'm trying to connect my site to sharepoint, however, I'm struggling to get a www-authenticate header from guzzle ...

`$request = $guzzle->request( 'GET', $this->site_url . '/_vti_bin/client.svc', [
	'http_errors' => false,
        'headers' => [
	    'Authorization' => 'Bearer'
	]
] );`

what is it supposed to be at /_vti_bin/client.svc ?
Thanks

**Comment by jakub-klapka** [comment]
Hi,
well, this is some service page, which should always exist in sharepoint. Whole request is kinda mock, because there is no "official" way, how to get realm from site URL. (At least it used to be like this)
This request will end with 401 Unauthorized, but in www-authenticate header, there is info about realm ID, which we need.

It's not cleanest way how to do that, but I didn't found any other...

What do you get for your site? It still works for me.

**Comment by thebaud2u** [comment]
Hi, thanks a lot for your fast response.

I managed to make the authorization work, on the other hand I can't upload anything because I don't understand the links I'm supposed to use to let Sharepoint reach my file.

You wrote : 

`$upload_result = $client->uploadFile(
	$refresh_token, 
	'/sites/mySite/myLibrary/',
	'file.txt',
	$this->transfer_storage->readStream( 'file.txt' )
);`

But what is '/sites/mySite/myLibrary/' ? Your laravel path url or the sharepoint path url ?

**Comment by jakub-klapka** [comment]
This is all sharepoint URL. In sharepoint, you have sites - in my example `mySite` and in those sites, you have to create document libraries - `myLibrary`.
At least in O365 sharepoint it's that way, but i suppose, that same applies to on-premise sharepoint...

**Comment by thebaud2u** [comment]
Ok, Thanks a lot.

In my case I've got this : 
`$upload = $client->uploadFile(
                $refreshToken,
                'Documents%20partages%2FTest',
                Storage::disk('public')->url('FO15.docx'),
                Storage::disk('public')->readStream('FO15.docx')
            );`

But it always end up with an 401 error but my file is reachable.
Any idea ?

**Comment by jakub-klapka** [comment]
`Documents%20partages%2FTest` does not seems like sharepoint document library URL. Are you sure, that you have created site and library in it? Is it O365 or on-premise sharepoint?

**Comment by thebaud2u** [comment]
The complete url is like this : https://companyName.sharepoint.com/sites/MySite/Documents%20partages/

Documents%20partages/ is Shared%20documents in english
In the code the url have a blank space but it automaticaly transform the whitespace in '%20'

**Comment by jakub-klapka** [comment]
The URL has to be full relative path, so in your case `/sites/MySite/Documents%20partages/`.

Try `$upload = $client->uploadFile( $refreshToken, '/sites/MySite/Documents%20partages/', Storage::disk('public')->url('FO15.docx'), Storage::disk('public')->readStream('FO15.docx') );`

**Comment by thebaud2u** [comment]
I'm sorry to bother you with this, but your code seems to be the only one to be working and I feel like I'm very close to make it work.

Here's the error I get : 
"Client error: `POST https://groupeatc.sharepoint.com/sites/Intrapiges-devgroupe6tmcom/_api/web/GetFolderByServerRelativeUrl('sites/Intrapiges-devgroupe6tmcom/Documents%20partages/')/Files/add(url='https://intrapiges-dev.groupe6tm.com/storage/FO15.docx',overwrite=true)` resulted in a `401 Unauthorized` response:
{"error_description":"Exception of type 'Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException' was thrown (truncated...)"

**Comment by jakub-klapka** [comment]
No prob, it seems, that you are really close :)

I see another error there, 3rd argument is just filename, you have full URL to your site. So instead of `Storage::disk('public')->url('FO15.docx')`, use just `FO15.docx`.

Although, the error, you are getting, seems to have something to do with authentication. Did you go through process of registering an Sharepoint App: _You will need those attributes, you can register Sharepoint App on: https://contoso.sharepoint.com/sites/MySite/_layouts/15/appregnew.aspx_?

**Comment by thebaud2u** [comment]
Ok, I've updated the third argument, thanks.

Yes, I followed your instructions and registered it. When I `$this->sharepointClient->makeClient($siteUrl, $appId, $appSecret, $redirectURI);` I'm redirected to a sharepoint page, where I'm asked to give consent. There is a dropdown list however, and I select 'Document'.
Then it comes back with the $authCode and uses it to refresh the token and then $client->uploadFile (etc...)

My first post was about the makeClient function, is my url for this correct : `https://groupeatc.sharepoint.com/sites/Intrapiges-devgroupe6tmcom/_vti_bin/client.svc` ?

**Comment by jakub-klapka** [comment]
Yes, this should work. If I make GET request for that URL, I do get realm in the header, so it should be OK.

Does it return same error even with repaired 3rd argument?
`Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException` does sound like some problem with Client ID or site URL. But this sharepoint API is so crapy, that it can mean anything :(

**Comment by thebaud2u** [comment]
Ok, thank you for taking the time to try the link with me.

Yes unfortunately it does give me the same error.
(1/1) ClientExceptionClient error: `POST https://groupeatc.sharepoint.com/sites/Intrapiges-devgroupe6tmcom/_api/web/GetFolderByServerRelativeUrl('sites/Intrapiges-devgroupe6tmcom/Documents%20partages/')/Files/add(url='FO15.docx',overwrite=true)` resulted in a `401 Unauthorized` response:{"error_description":"Exception of type 'Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException' was thrown (truncated...)
--
in RequestException.php line 113

Yeah I totaly agree and like I said, I haven't been able to find a single working example besides yours, so that's why I've been working with your code for the past few days.

I'm gonna try to register a new sharepoint App to see if it changes anything.

Thanks again Jakub

**Comment by thebaud2u** [comment]
Ok, now I got a different error : 
Client error: `POST https://company/sites/MySite/_api/web/GetFolderByServerRelativeUrl('sites/Intrapiges-devgroupe6tmcom/Documents%20partages/')/Files/add(url='FO15.docx',overwrite=true)` resulted in a `404 Not Found` response:
{"error":{"code":"-2147024893, System.IO.DirectoryNotFoundException","message":{"lang":"fr-FR","value":"Fichier introuva (truncated...)

**Comment by thebaud2u** [comment]
Ok everything works fine now ! I left a mistake in my code regarding the siteUrl ... -_- 

Thanks a lot for your help !

**Comment by jakub-klapka** [comment]
Perfect, I'm glad that helps ;-)
